### ISSUE TITLE
Bad allocation

### ISSUE THREAD

**Issue by skampus** [p0cisk/osmSearch#1]
search works but a after that it shows a pop up window with this error message "bad allocation". push ok but immediatly another one appears.

qgis master ver. 23782b7

**Comment by p0cisk** [comment]
Hi skampus,
I can't replicate this error on Win 7 64-bit and Linux Mint 14 32-bit (latest master).
What system you are using?
When error occurs - after displaying all/part of search results or when you're select item?

**Comment by skampus** [comment]
hi piotr, now it works.
thank you
