### ISSUE TITLE
OsmSearch :  add object in a new layer  has  epsg 2154

### ISSUE THREAD

**Issue by geodrinx** [p0cisk/osmSearch#2]
as in object:  adding new layer,  it has epsg:2154  instead of  4326 ...

I found that  2154 is hardcoded into  nominatim_dlg.py   (nominatim QGis plugin ...)

**Comment by p0cisk** [comment]
Hi geodrinx
This bug is probably related with OSM place search QGIS plugin by Xavier Culos with has bug tracker at http://hub.qgis.org/projects/nominatim/issues.
This is tracker for osmSearch plugin
