### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by ghost** [p0cisk/osmSearch#3]
It can't handle the danish letters, æ, ø å.

**Comment by p0cisk** [comment]
Which version you are using?
It should be fixed since version 0.3.1. 72c58f9b.
This is screen from QGSI 2.1 master, Win7:
![osmsearch](https://f.cloud.github.com/assets/1368688/1674913/a1a638ce-5d00-11e3-8d6b-7e85926e8fa7.png)
It's seems that no one has approved fixed version in http://plugins.qgis.org/plugins/osmSearch/ - I was upload it June 30!

**Comment by ghost** [comment]
I get this error:

Traceback (most recent call last):
  File "C:\Documents and Settings\Per Gammerath/.qgis2/python/plugins\osmSearch\osmSearchDialog.py", line 75, in startSearch
    params = urllib.urlencode({'q': text,'format': 'json','polygon_text':'1'})
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\urllib.py", line 1326, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc6' in position 0: ordinal not in range(128)

Python-version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS-version:
2.0.1-Dufour Dufour, ebebdf3

Python-sti: ['C:\Documents and Settings\Per Gammerath/.qgis2/python/plugins\processing', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python', 'C:\Documents and Settings\Per Gammerath/.qgis2/python', 'C:\Documents and Settings\Per Gammerath/.qgis2/python/plugins', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISDU~1\bin\python27.zip', 'C:\PROGRA~1\QGISDU~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISDU~1\bin', 'C:\PROGRA~1\QGISDU~1\apps\Python27', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISDU~1\apps\qgis\python\plugins\fTools\tools', 'C:/Documents and Settings/Per Gammerath/Dokumenter/QGIS/Projektomr\xc3\xa5der']

I'm not sure if I'm using the latest version, but I have just installed the plugin today, so I figured it was the latest.

**Comment by ghost** [comment]
I got it working now. Copied the bug fix and replaced the old code. Thanks a lot.

Would you consider having osmSearch predict the address as you type?

**Comment by p0cisk** [comment]
You have version 0.3. I was uploaded version 0.3.1. into QGIS server but no one reviewed it since 30 June.

If you thinking about autocomplete like in google than Nominatim usage policy don't allow this: https://wiki.openstreetmap.org/wiki/Nominatim_usage_policy (see Unacceptable Use).
Autocomplete is only from cache of earlier entries.

**Comment by ghost** [comment]
Yes, I was thinking of auto completion. Thank you for your reply.
We actually have our own address layer in our maps, and it would have been really handy with a plugin that could search in a particular layer and in particular columns. Look in myLayer for like %X% in Roads and %Y% in HouseNumber.

**Comment by p0cisk** [comment]
I see, you mean autocomplete from user predefined data.
Please open new ticket with enhancement flag and describe this feature.

**Comment by ghost** [comment]
I don't know how to open a new ticket. Is it the same as a new issue?
Github is very confusing.
Den 05/12/2013 17.30 skrev "Piotr Pociask" notifications@github.com:

**Comment by p0cisk** [comment]
Yes, you are correct. Sorry for misleading.
